---
title: "fungal microbiome"
author: "Elizabeth Green"
date: "2023-05-08"
output: html_document
---

```{r}
library(vegan)
library(tidyverse)
library(lubridate)
library(emmeans)
library(viridis)
library(DESeq2)
library(plotrix)
library(lme4)
library(lmerTest)
library(epifitter)
library(RColorBrewer)
library(scales)
library(MuMIn)
library(patchwork)
library(indicspecies)

theme_set(theme_bw())
nutrient_colors = c("none" = "#A1D99B",
                    "low" = "#41AB5D",
                    "high" = "#005A32")
```

#loading data
```{r}
metadata <- read.csv("data/metadata.csv") %>%
  mutate(survey.date = as.factor(mdy(survey.date))) %>%
  dplyr::rename(Date = survey.date) %>%
  mutate(Date = ifelse(Date == "2022-04-30", "2022-04-29", as.character(Date))) %>%
  mutate(Date = ifelse(Date == "2022-06-09", "2022-06-07", as.character(Date))) %>%
  mutate(Date = ymd(Date)) %>%
  mutate(DateTreatment = paste(as.factor(Date), Treatment, sep = "_"))

counts <- read.csv("data/counts.csv") %>%
  pivot_longer(cols = !sample.ID,
               names_to = "OTU",
               values_to = "counts") %>%
  mutate(OTU = str_replace(OTU, "X", ""))

counts <- read.csv("data/counts4.csv") %>%
  pivot_longer(cols = !c(OTU, sequence),
               names_to = "sample.id",
               values_to = "counts") %>%
  na.omit()

assignments <- read.csv("data/assignments4.csv") %>%
  filter(sequence != "")
```

#filtering and normalizing data
```{r}
otu_filter <- counts %>%
  filter(counts > 25) %>% #greater than 25 counts per ASV per sample
  group_by(OTU) %>%
  summarise(freq = n()) %>%
  filter(freq > 5) #appear more than 5 times in the data

counts <- counts %>%
  inner_join(otu_filter, by = "OTU")

counts_sample <- counts %>%
  group_by(sample.id) %>%
  summarise(sum = sum(counts)) %>%
  filter(sum > 2000)  #samples with more than 500 reads

counts_sample %>%
  ggplot(aes(x = sum)) + geom_histogram(bins = 40) +
  scale_x_continuous(labels = scales::comma) +
  labs(x = "Sampling Depth", y = "Number of Samples") +
    theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 14))


counts_sample %>% summarize(median(sum))

counts <- counts_sample %>%
  inner_join(counts, by = "sample.id")

counts_wide <- counts %>%
  dplyr::select(sample.id, counts, OTU) %>%
  pivot_wider(names_from = "OTU", values_from = "counts") %>%
  column_to_rownames("sample.id") %>%
  mutate(across(where(is.numeric), ~ .x + 1))

counts_norm <- varianceStabilizingTransformation(as.matrix(counts_wide), blind = F) ##normalizing for ordination

```

#richness
```{r}
counts_summary <- counts %>%
  inner_join(metadata, by = "sample.id") %>%
  filter(counts != 0) %>%
  group_by(sample.id, Date, Treatment, Block, Column, Row, Plot, plate, sum) %>%
  summarise(counts = sum(counts),
          OTUs = n()) %>%
  mutate(Treatment = factor(Treatment, levels = c("none", "low", "high")))

richness <- counts_summary %>%
  group_by(sample.id, Date, Treatment, Plot, Block, plate, sum) %>%
  summarise(OTUs = sum(OTUs))

richness.fig <- richness %>%
  ggplot(aes(x = Date, y = OTUs, color = Treatment)) +
  stat_smooth(method = "lm", formula = y ~ x, size = 1, se = F) +        
  geom_point(aes(color = Treatment), position = position_jitter(width = 5), alpha = 0.8) +
  scale_color_manual(values = nutrient_colors, name = "Nutrient Addition") +
  labs(y = "Total Observed Taxa", x = "Survey Date") +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 14))

richness <- richness %>%
  mutate(Date2 = as.numeric(Date)^2)

rich.mod <- lmer(log10(OTUs) ~ sum + (Date) * Treatment + (1|Block/Plot), data = richness)
qnorm(residuals(rich.mod))
summary(rich.mod)
anova(rich.mod, mode = "satterthwaite")
AIC(rich.mod)
emmeans(rich.mod, pairwise ~ Treatment)
```

#shannon diversity
```{r}
shannon <- diversity(counts_wide)

shannon <- as.data.frame(shannon) %>%
  rownames_to_column("sample.id") %>%
  inner_join(richness, by = "sample.id")

shannon.fig <- shannon %>%
  ggplot(aes(x = Date, y = shannon)) +
  stat_smooth(method = "lm", formula = y ~ x + I(x^2), size = 1, se = F) +
  geom_point(aes(color = Treatment), alpha = 0.8, position = position_jitter(width = 5)) +
  scale_color_manual(values = nutrient_colors, name = "Nutrient Addition") +
  labs(x = "Survey Date", y = "Shannon Diversity Index") +
    theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 14))

shannon <- shannon %>%
  mutate(Date2 = as.numeric(Date)^2)

shannon.mod <- lmer(log10(shannon) ~ sum + (Date + Date2) * Treatment + (1 |Block/Plot), data = shannon)
qqnorm(residuals(shannon.mod))
summary(shannon.mod)
anova(shannon.mod, mode = "satterthwaite")
AIC(shannon.mod)
```

##evenness
```{r}
evenness <- shannon %>%
  mutate(evenness = shannon/log(OTUs))

evenness.fig <- evenness %>%
  ggplot(aes(x = Date, y = evenness)) +
  stat_smooth(method = "lm", formula = y ~ x + I(x^2), size = 1, se = F) +        
  geom_point(aes(color = Treatment), position = position_jitter(width = 5), alpha = 0.8) +
  scale_color_manual(values = nutrient_colors, name = "Nutrient Addition") +
  labs(x = "Survey Date", y = "Evenness") +
    theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 14))

evenness <- evenness %>%
   mutate(Date2 = as.numeric(Date)^2) 
evenness.mod <- lmer(log10(evenness) ~ sum + (Date + Date2) * Treatment + (1|Block/Plot), data = evenness)
qqnorm(residuals(evenness.mod))
summary(evenness.mod)
anova(evenness.mod, mode = "satterthwaite")
AIC(evenness.mod)
```


#bray curtis
```{r}
metadata_norm <- metadata %>%
  left_join(counts, by = "sample.id") %>%
  group_by(sample.id) %>%
  summarise(Treatment = unique(as.factor(Treatment)),
            Date = as.factor(unique(Date)),
            Plot = unique(Plot),
            Block = unique(Block))

bc_dist <- vegdist(abs(counts_norm), method = "bray")
bc_nmds <- metaMDS(bc_dist)

bc_df <- scores(bc_nmds, display = "sites") %>% 
  as.data.frame() %>% 
  rownames_to_column("sample.id") %>% 
  inner_join(metadata, by = "sample.id") %>%
  mutate(Treatment = factor(Treatment, levels = c("none", "low", "high")))
  

bc <- ggplot(bc_df, aes(x = NMDS1, y = NMDS2, group = Date, color = as.factor(Date))) +
  geom_point(size = 2, alpha = 0.8) +
  stat_ellipse(linetype = 2, size = 1) +
  scale_color_brewer(palette="Dark2", name = "Date") +
    theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 14)) + ggtitle("Complete Community")
bc

bc_fert <- ggplot(bc_df, aes(x = NMDS1, y = NMDS2, group = Treatment, color = Treatment)) +
  geom_point(size = 2, alpha = 0.8) +
  stat_ellipse(linetype = 2, size = 1) +
  scale_color_manual(values=nutrient_colors, name = "Nutrient Addition") +
      theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 14)) + ggtitle("Complete Community")
bc_fert

bc.perm <- adonis2(bc_dist ~ sum + Date * Treatment, data = shannon, strata = shannon$Block/shannon$Plot)
bc.perm

bc.beta <- betadisper(bc_dist, group = shannon$Date)
anova(bc.beta)
bc.pmod <- permutest(bc.beta , permutations = 99, pairwise = TRUE)
bc.pmod

bc.beta.df <- as.data.frame(bc.beta$distances) %>%
  rownames_to_column("sample.id") %>%
  inner_join(shannon, by = "sample.id") %>%
  rename("bc.beta$distances" = "distance") %>%
  mutate(distance = distance,
         Treatment = factor(Treatment, levels = c("none", "low", "high")))

beta.fig <- bc.beta.df %>%
  ggplot(aes(x = Date, y = (distance), color = Treatment)) +
  stat_smooth(method = "lm", formula = y ~ x, size = 1, se = F) +        
  geom_point(aes(color = Treatment), position = position_jitter(width = 5), alpha = 0.8) +
  scale_color_manual(values = nutrient_colors, name = "Nutrient Addition") +
      theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 14)) +
  labs(x = "Survey Date", y = "Distance to Centroid") + ggtitle("Complete Community")

bc.beta.df <- bc.beta.df %>%
   mutate(Date2 = as.numeric(Date)^2) 
bc.beta.mod <- lmer(log(distance)~ sum + (Date) * Treatment + (1|Block/Plot), data = bc.beta.df)
qqnorm(residuals(bc.beta.mod))
summary(bc.beta.mod)
anova(bc.beta.mod)
AIC(bc.beta.mod)
```

#Core Taxa as defined by Shade and Stopnisek 2019
```{r}
rep <- counts %>%
  filter(counts > 0) %>%
  left_join(metadata, by = "sample.id") %>%
  group_by(OTU, sequence, Date) %>%
  summarise(n = n()) %>%
  mutate(rep = case_when(n >= 36 ~ 1,
                               n < 36 ~ 0)) %>%
  select(-n)

time <- counts %>%
  filter(counts > 0) %>%
  left_join(metadata, by = "sample.id") %>%
  group_by(OTU, sequence, Date) %>%
  summarise(n = n()) %>%
  mutate(occupancy = n/36) %>%
  select(-n)

core <- full_join(rep, time, by = c("OTU", "sequence", "Date")) %>%
  group_by(OTU, sequence) %>%
  summarise(sum_occupancy = sum(occupancy),
            sum_rep = sum(rep),
            index = (sum_occupancy + sum_rep)/2) %>%
  arrange(desc(index))



sort_and_split_by_index <- function(df, index_col) {
  # Sort dataframe by index values
  df <- df[order(df[[index_col]]), ]
  
  # Get unique index values in descending order
  unique_indices <- rev(unique(df[[index_col]]))
  
  # Split dataframe into multiple dataframes
  split_dfs <- lapply(unique_indices, function(i) {
    subset_df <- df[df[[index_col]] >= i, ]
    return(subset_df)
  })
  
  return(split_dfs)
}

  
split_core <- sort_and_split_by_index(core, "index")

core_wide <- lapply(split_core, function(x) {
  x %>%
  left_join(counts, by = "OTU") %>%
  dplyr::select(sample.id, counts, OTU) %>%
  group_by(sample.id, OTU) %>%
  summarise(counts = unique(counts)) %>%
  pivot_wider(names_from = "OTU", values_from = "counts") %>%
  column_to_rownames("sample.id") %>%
  mutate(across(where(is.numeric), ~ .x + 1))
  })

core_bc <- lapply(core_wide, function(x) {
  vegdist(abs(x), method = "bray")
})

core_mean <- lapply(core_bc, mean)

core_change <- lapply(core_mean, function(x) {
  1-x/core_mean[[142]]
})


core_change2 <- data.frame(core_change) %>%
  pivot_longer(everything(), names_to = "name", values_to = "change") %>%
  select(change)

core_mean2 <- data.frame(core_mean) %>%
  pivot_longer(everything(), names_to = "name", values_to = "mean") %>%
  select(mean)


core3 <- cbind(core %>% group_by(index) %>% summarise(unique(index)) %>% arrange(desc(index)), core_mean2, core_change2)

core2 <- core3 %>%
  group_by(index) %>%
  summarize(mean = mean(mean),
            change = mean(change)) %>%
  arrange(desc(index)) %>%
  rownames_to_column(var = "rownum")

core.fig <- core2 %>%
  ggplot(aes(x = as.numeric(index), y = as.numeric(mean))) +
  geom_line() +
  geom_point() +
  geom_hline(yintercept = 0.751, color = "blue") +
  scale_y_continuous(expand = c(0, 0)) +
  labs(x = "ASVs by Occupancy", y = "% Bray Curtis Dissimilarity Attributed to Ranked ASVs") +
  scale_x_reverse() +
  theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 14))

core.fig2 <- core2 %>%
  ggplot(aes(x = as.numeric(rownum), y = as.numeric(change))) +
  geom_line() +
  geom_point() +
  geom_hline(yintercept = 0.02, color = "blue") +
  scale_y_continuous(expand = c(0, 0)) +
  labs(x = "Index Rank", y = "Difference in Dissimilarity Explained") +
   theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 14))
  
core <- core %>%
  filter(index >= 1.27) %>%
  left_join(assignments, by = "sequence")

write_csv(core, "core.csv")

```

#core bray curtis
```{r}
core_wide <- core %>%
  filter(index >= 1.27) %>%
  left_join(counts, by = "OTU") %>%
  dplyr::select(sample.id, counts, OTU) %>%
  group_by(sample.id, OTU) %>%
  summarise(counts = unique(counts)) %>%
  pivot_wider(names_from = "OTU", values_from = "counts") %>%
  column_to_rownames("sample.id") %>%
  mutate(across(where(is.numeric), ~ .x + 1))

core_norm <- varianceStabilizingTransformation(as.matrix(core_wide), blind = F)

core_bc_dist <- vegdist(abs(core_norm), method = "bray")
core_nmds <- metaMDS(core_bc_dist)

core_bc_df <- scores(core_nmds, display = "sites") %>% 
  as.data.frame() %>% 
  rownames_to_column("sample.id") %>% 
  inner_join(shannon, by = "sample.id") %>%
  mutate(Treatment = factor(Treatment, levels = c("none", "low", "high")))

plot_core_fert <- ggplot(core_bc_df, aes(x = NMDS1, y = NMDS2, group = Treatment, color = Treatment)) +
  geom_point(size = 2, alpha = 0.8) +
  stat_ellipse(linetype = 2, size = 1) +
  scale_color_manual(values = nutrient_colors, name = "Nutrient Addition") +
    theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 14)) + ggtitle("Core Community")
plot_core_fert

plot_core <- ggplot(core_bc_df, aes(x = NMDS1, y = NMDS2, group = as.factor(Date), color = as.factor(Date))) +
  geom_point(size = 2, alpha = 0.8) +
  stat_ellipse(linetype = 2, size = 1) +
  scale_color_brewer(palette = "Dark2", name = "Date") +
    theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 14)) + ggtitle("Core Community")
plot_core

core.perm <- adonis2(core_bc_dist ~ sum + Date * Treatment, data = shannon, strata = shannon$Block/shannon$Plot, na.action = na.exclude)
core.perm

core.beta <- betadisper(core_bc_dist, group = core_bc_df$Date)
anova(core.beta)

core.beta.df <- as.data.frame(core.beta$distances) %>%
  rownames_to_column("sample.id") %>%
  inner_join(core_bc_df, by = "sample.id") %>%
  mutate(Treatment = factor(Treatment, levels = c("none", "low", "high"))) %>%
  rename("core.beta$distances" = "distance")

core.beta.fig <- core.beta.df %>%
  ggplot(aes(x = Date, y = (distance), color = Treatment)) +
  stat_smooth(method = "lm", formula = y ~ x, size = 1, se = F) +        
  geom_point(aes(color = Treatment), position = position_jitter(width = 5), alpha = 0.8) +
  scale_color_manual(values = nutrient_colors, name = "Nutrient Addition") +
      theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 14)) +
  labs(x = "Survey Date", y = "Distance to Centroid") +
  ggtitle("Core Community")

core.beta.df <- core.beta.df %>%
  mutate(Date2 = as.numeric(Date)^2)
core.beta.mod <- lmer(log10(distance) ~ sum + (Date) * Treatment + (1 |Block/Plot), data = core.beta.df)
qqnorm(residuals(core.beta.mod))
summary(core.beta.mod)
anova(core.beta.mod)
emmeans(core.beta.mod, pairwise ~ Treatment)
AIC(core.beta.mod)
```

#core richness
```{r}
core_counts <- counts %>%
  inner_join(core, by = "OTU") %>%
  filter(index >= 1.27)

core_counts_summary <- core_counts %>%
  inner_join(metadata, by = "sample.id") %>%
  filter(counts != 0) %>%
  group_by(sample.id, Date, Treatment, Block, Column, Row, Plot, plate, sum) %>%
  summarise(counts = sum(counts),
          OTUs = n()) %>%
  mutate(Treatment = factor(Treatment, levels = c("none", "low", "high")))

core_richness <- core_counts_summary %>%
  group_by(sample.id, Date, Treatment, Plot, Block, plate, sum) %>%
  summarise(OTUs = sum(OTUs))

core.richness.fig <- core_richness %>%
ggplot(aes(x = Date, y = OTUs, color = Treatment)) +
  stat_smooth(method = "lm", formula = y ~ x + I(x^2), size = 1, se = F) +
  geom_point(aes(color = Treatment), alpha = 0.8, position = position_jitter(width = 5)) +
  scale_color_manual(values = nutrient_colors, name = "Nutrient Addition") +
  labs(x = "Survey Date", y = "Total Observed Taxa of Core") +
    theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 14))

core_richness <- core_richness %>%
  mutate(Date2 = as.numeric(Date)^2)

core.rich.mod <- lmer(log10(OTUs) ~ sum + (Date + Date2) * Treatment + (1|Block/Plot), data = core_richness)
qnorm(residuals(core.rich.mod))
summary(core.rich.mod)
anova(core.rich.mod, mode = "satterthwaite")
AIC(core.rich.mod)
```

#core shannon diversity
```{r}
core.shannon <- diversity(core_wide)

core.shannon <- as.data.frame(core.shannon) %>%
  rownames_to_column("sample.id") %>%
  inner_join(core_richness, by = "sample.id")

core.shannon.fig <- core.shannon %>%
  ggplot(aes(x = Date, y = core.shannon)) +
  stat_smooth(method = "lm", formula = y ~ x + I(x^2), size = 1, se = F) +
  geom_point(aes(color = Treatment), alpha = 0.8, position = position_jitter(width = 5)) +
  scale_color_manual(values = nutrient_colors, name = "Nutrient Addition") +
  labs(x = "Survey Date", y = "Shannon Diversity Index of Core") +
    theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 14))

core.shannon <- core.shannon %>%
  mutate(Date2 = as.numeric(Date)^2)

core.shannon.mod <- lmer(log10(core.shannon) ~ sum + (Date + Date2) * Treatment + (1 |Block/Plot), data = core.shannon)
qqnorm(residuals(core.shannon.mod))
summary(core.shannon.mod)
anova(core.shannon.mod)
AIC(core.shannon.mod)
```

##core evenness
```{r}
core.evenness <- core.shannon %>%
  mutate(core.evenness = core.shannon/log(OTUs))

core.evenness.fig <- core.evenness %>%
  ggplot(aes(x = Date, y = core.evenness)) +
  stat_smooth(method = "lm", formula = y ~ x + I(x^2), size = 1, se = F) +
  geom_point(aes(color = Treatment), alpha = 0.8, position = position_jitter(width = 5)) +
  scale_color_manual(values = nutrient_colors, name = "Nutrient Addition") +
  labs(x = "Survey Date", y = "Evenness of Core") +
    theme(axis.text = element_text(size = 12),
        axis.title = element_text(size = 14),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 14))

core.evenness <- core.evenness %>%
  mutate(Date2 = as.numeric(Date)^2)

core.evenness.mod <- lmer(log10(core.evenness) ~ sum + (Date + Date2) * Treatment + (1 |Block/Plot), data = core.evenness)
qqnorm(residuals(core.evenness.mod))
summary(core.evenness.mod)
anova(core.evenness.mod, mode = "satterthwaite")
AIC(core.evenness.mod)
```

##figures
```{r}
(shannon.fig + xlab(NULL)) / core.shannon.fig + plot_layout(guides = "collect") + plot_annotation(tag_levels = 'A')
(richness.fig + xlab(NULL)) / core.richness.fig + plot_layout(guides = "collect") +  plot_annotation(tag_levels = 'A')
(evenness.fig + xlab(NULL)) / core.evenness.fig + plot_layout(guides = "collect") + plot_annotation(tag_levels = 'A')

(bc) / (plot_core) + plot_layout(guides = "collect") + plot_annotation(tag_levels = 'A')

(bc_fert) / (plot_core_fert) + plot_layout(guides = "collect") + plot_annotation(tag_levels = 'A')

(beta.fig + xlab(NULL)) / (core.beta.fig) + plot_layout(guides = "collect") + plot_annotation(tag_levels = 'A')

(infect_rhiz + xlab(NULL)) / (core_infect) + plot_layout(guides = "collect") + plot_annotation(tag_levels = 'A')

(core.fig + xlab(NULL)) / core.fig2 + plot_annotation(tag_levels = 'A')

```

##indicator species analysis
```{r}
nutrientsbydate <- richness %>%
  mutate(DateTreatment = paste(Date, Treatment),
         DateBlock = paste(Date, Block))
nutrientsbyblock <- nutrientsbydate$DateBlock
nutrientsbydate <- nutrientsbydate$DateTreatment

indicator <- multipatt(counts_wide, richness$Plot, control = how(nperm=999))
summary(indicator)

```

